/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try { // try catch is only necessary because we are throwing an exception, if we overload the constructor with default values, we can remove the try catch
            Card card = new Card();
            card.setFromWord("hello");
            card.setToWord("hola");
            card.verify();
            System.out.println("Card created successfully!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
